/**
 * Localization helper for JellyHA Library Card
 */

const translations: Record<string, Record<string, string>> = {
    en: {
        loading: 'Loading…',
        no_media: 'No recent media found',
        error: 'Error loading media',
        new: 'New',
        minutes: 'min',
        play: 'Play',
        pause: 'Pause',
        stop: 'Stop',
        nothing_playing: 'Nothing is currently playing',
        entity_not_found: 'Entity not found',
        rewinding: 'REWINDING',
        no_trailer: 'No trailer available',

        // Editor
        'editor.entity': 'Entity',
        'editor.title': 'Title',
        'editor.show_title': 'Show Title',
        'editor.show_year': 'Show Year',
        'editor.show_runtime': 'Show Runtime',
        'editor.show_rating': 'Show Rating',
        'editor.show_genres': 'Show Genre',
        'editor.show_client': 'Show Jellyfin Client',
        'editor.show_background': 'Show Background',
        'editor.show_media_type_badge': 'Show Media Type Badge',
        'editor.show_watched_status': 'Show Watched Status',
        'editor.show_date_added': 'Show Date Added',
        'editor.show_description': 'Show Description',
        'editor.layout': 'Layout',
        'editor.layout_carousel': 'Carousel',
        'editor.layout_grid': 'Grid',
        'editor.layout_list': 'List',
        'editor.media_type': 'Media Type',
        'editor.media_type_both': 'Movies & TV Shows',
        'editor.media_type_movies': 'Movies Only',
        'editor.media_type_series': 'TV Shows Only',
        'editor.media_type_next_up': 'Next Up',
        'editor.items_per_page': 'Items Per Page',
        'editor.max_pages': 'Max Pages (0 = no limit)',
        'editor.auto_swipe': 'Auto Swipe (sec, 0 = off)',
        'editor.new_badge_days': 'New Badge Days (0 = off)',
        'editor.click_action': 'Short Press (Click)',
        'editor.hold_action': 'Long Press (Hold)',
        'editor.action_jellyfin': 'Open in Jellyfin',
        'editor.action_cast': 'Cast to Chromecast',
        'editor.action_more_info': 'More Information',
        'editor.action_trailer': 'Watch Trailer',
        'editor.action_none': 'No Action',
        'editor.default_cast_device': 'Default Cast Device',
        'editor.show_now_playing_overlay': 'Show "Now Playing" Overlay on Posters',
        'editor.metadata_position': 'Metadata Position',
        'editor.metadata_below': 'Below',
        'editor.metadata_above': 'Above',
        'editor.sort_order': 'Sort Order',
        'editor.sort_date_added_desc': 'Date Added (Newest First)',
        'editor.sort_date_added_asc': 'Date Added (Oldest First)',
        'editor.sort_title_asc': 'Title (A-Z)',
        'editor.sort_title_desc': 'Title (Z-A)',
        'editor.sort_year_desc': 'Year (Newest First)',
        'editor.sort_year_asc': 'Year (Oldest First)',
        'editor.sort_last_played_desc': 'Last Played (Newest First)',
        'editor.sort_last_played_asc': 'Last Played (Oldest First)',
        'editor.enable_pagination': 'Enable Pagination',
        'editor.show_pagination_dots': 'Show Pagination Dots',
        'editor.filter_watch_status': 'Filter Watch Status',
        'editor.filter_all': 'All',
        'editor.filter_unwatched': 'Unwatched',
        'editor.filter_watched': 'Watched',
        'editor.filter_favorites': 'Filter Favorites',
        'editor.filter_new_items': 'Filter New Items',
        'editor.columns': 'Columns',
        'editor.rows': 'Rows',
        'editor.now_playing_sensor': 'Now Playing Sensor',
        'editor.auto': 'Auto',
    },
    de: {
        loading: 'Laden…',
        no_media: 'Keine Medien gefunden',
        error: 'Fehler beim Laden',
        new: 'Neu',
        minutes: 'Min',
        play: 'Abspielen',
        pause: 'Pause',
        stop: 'Stopp',
        nothing_playing: 'Nichts wird abgespielt',
        entity_not_found: 'Entität nicht gefunden',
        rewinding: 'SPULEN',
        no_trailer: 'Kein Trailer verfügbar',

        // Editor
        'editor.entity': 'Entität',
        'editor.title': 'Titel',
        'editor.show_title': 'Titel anzeigen',
        'editor.show_year': 'Jahr anzeigen',
        'editor.show_runtime': 'Laufzeit anzeigen',
        'editor.show_rating': 'Bewertung anzeigen',
        'editor.show_genres': 'Genre anzeigen',
        'editor.show_client': 'Jellyfin-Client anzeigen',
        'editor.show_background': 'Hintergrund anzeigen',
        'editor.show_media_type_badge': 'Medientyp-Abzeichen anzeigen',
        'editor.show_watched_status': 'Gesehen-Status anzeigen',
        'editor.show_date_added': 'Hinzugefügt am anzeigen',
        'editor.show_description': 'Beschreibung anzeigen',
        'editor.layout': 'Layout',
        'editor.layout_carousel': 'Karussell',
        'editor.layout_grid': 'Raster',
        'editor.layout_list': 'Liste',
        'editor.media_type': 'Medientyp',
        'editor.media_type_both': 'Filme & Serien',
        'editor.media_type_movies': 'Nur Filme',
        'editor.media_type_series': 'Nur Serien',
        'editor.media_type_next_up': 'Als Nächstes',
        'editor.items_per_page': 'Elemente pro Seite',
        'editor.max_pages': 'Max. Seiten (0 = kein Limit)',
        'editor.auto_swipe': 'Auto-Swipe (Sek., 0 = aus)',
        'editor.new_badge_days': 'Neu-Abzeichen Tage (0 = aus)',
        'editor.click_action': 'Kurz drücken (Klick)',
        'editor.hold_action': 'Lang drücken (Halten)',
        'editor.action_jellyfin': 'In Jellyfin öffnen',
        'editor.action_cast': 'An Chromecast senden',
        'editor.action_more_info': 'Mehr Informationen',
        'editor.action_trailer': 'Trailer ansehen',
        'editor.action_none': 'Keine Aktion',
        'editor.default_cast_device': 'Standard-Chromecast-Gerät',
        'editor.show_now_playing_overlay': '"Jetzt läuft"-Overlay anzeigen',
        'editor.metadata_position': 'Metadaten-Position',
        'editor.metadata_below': 'Darunter',
        'editor.metadata_above': 'Darüber',
        'editor.sort_order': 'Sortierung',
        'editor.sort_date_added_desc': 'Hinzugefügt (Neueste zuerst)',
        'editor.sort_date_added_asc': 'Hinzugefügt (Älteste zuerst)',
        'editor.sort_title_asc': 'Titel (A-Z)',
        'editor.sort_title_desc': 'Titel (Z-A)',
        'editor.sort_year_desc': 'Jahr (Neueste zuerst)',
        'editor.sort_year_asc': 'Jahr (Älteste zuerst)',
        'editor.sort_last_played_desc': 'Zuletzt gespielt (Neueste zuerst)',
        'editor.sort_last_played_asc': 'Zuletzt gespielt (Älteste zuerst)',
        'editor.enable_pagination': 'Seitennummerierung aktivieren',
        'editor.show_pagination_dots': 'Paginierungspunkte anzeigen',
        'editor.filter_watch_status': 'Gesehen-Status filtern',
        'editor.filter_all': 'Alle',
        'editor.filter_unwatched': 'Ungesehen',
        'editor.filter_watched': 'Gesehen',
        'editor.filter_favorites': 'Favoriten filtern',
        'editor.filter_new_items': 'Neue Elemente filtern',
        'editor.columns': 'Spalten',
        'editor.rows': 'Zeilen',
        'editor.now_playing_sensor': 'Sensor für aktuelle Wiedergabe',
        'editor.auto': 'Automatisch',
    },
    fr: {
        loading: 'Chargement…',
        no_media: 'Aucun média récent trouvé',
        error: 'Erreur de chargement des médias',
        new: 'Nouveau',
        minutes: 'min',
        play: 'Lire',
        pause: 'Pause',
        stop: 'Arrêt',
        nothing_playing: 'Rien en lecture',
        entity_not_found: 'Entité non trouvée',
        rewinding: 'BOBINAGE',
        no_trailer: 'Aucune bande-annonce disponible',

        // Editor
        'editor.entity': 'Entité',
        'editor.title': 'Titre',
        'editor.show_title': 'Afficher le titre',
        'editor.show_year': 'Afficher l\'année',
        'editor.show_runtime': 'Afficher la durée',
        'editor.show_rating': 'Afficher la note',
        'editor.show_genres': 'Afficher le genre',
        'editor.show_client': 'Afficher le client Jellyfin',
        'editor.show_background': 'Afficher l\'arrière-plan',
        'editor.show_media_type_badge': 'Afficher le badge de type de média',
        'editor.show_watched_status': 'Afficher le statut de visionnage',
        'editor.show_date_added': 'Afficher la date d\'ajout',
        'editor.show_description': 'Afficher la description',
        'editor.layout': 'Mise en page',
        'editor.layout_carousel': 'Carrousel',
        'editor.layout_grid': 'Grille',
        'editor.layout_list': 'Liste',
        'editor.media_type': 'Type de média',
        'editor.media_type_both': 'Films et séries',
        'editor.media_type_movies': 'Films seulement',
        'editor.media_type_series': 'Séries seulement',
        'editor.media_type_next_up': 'À suivre',
        'editor.items_per_page': 'Éléments par page',
        'editor.max_pages': 'Pages max (0 = illimité)',
        'editor.auto_swipe': 'Défilement auto (sec, 0 = désactivé)',
        'editor.new_badge_days': 'Jours badge nouveau (0 = désactivé)',
        'editor.click_action': 'Appui court (Clic)',
        'editor.hold_action': 'Appui long (Maintenir)',
        'editor.action_jellyfin': 'Ouvrir dans Jellyfin',
        'editor.action_cast': 'Caster sur Chromecast',
        'editor.action_more_info': 'Plus d\'informations',
        'editor.action_trailer': 'Voir la bande-annonce',
        'editor.action_none': 'Aucune action',
        'editor.default_cast_device': 'Appareil Cast par défaut',
        'editor.show_now_playing_overlay': 'Superposition "En lecture"',
        'editor.metadata_position': 'Position des métadonnées',
        'editor.metadata_below': 'Dessous',
        'editor.metadata_above': 'Dessus',
        'editor.sort_order': 'Ordre de tri',
        'editor.sort_date_added_desc': 'Date d\'ajout (Plus récent)',
        'editor.sort_date_added_asc': 'Date d\'ajout (Plus ancien)',
        'editor.sort_title_asc': 'Titre (A-Z)',
        'editor.sort_title_desc': 'Titre (Z-A)',
        'editor.sort_year_desc': 'Année (Plus récent)',
        'editor.sort_year_asc': 'Année (Plus ancien)',
        'editor.sort_last_played_desc': 'Dernière lecture (Plus récent)',
        'editor.sort_last_played_asc': 'Dernière lecture (Plus ancien)',
        'editor.enable_pagination': 'Activer la pagination',
        'editor.show_pagination_dots': 'Afficher les points de pagination',
        'editor.filter_watch_status': 'Filtrer le statut de visionnage',
        'editor.filter_all': 'Tous',
        'editor.filter_unwatched': 'Non vus',
        'editor.filter_watched': 'Vus',
        'editor.filter_favorites': 'Filtrer les favoris',
        'editor.filter_new_items': 'Filtrer les nouveaux éléments',
        'editor.columns': 'Colonnes',
        'editor.rows': 'Lignes',
        'editor.now_playing_sensor': 'Capteur de lecture en cours',
        'editor.auto': 'Auto',
    },
    es: {
        loading: 'Cargando…',
        no_media: 'No se encontraron medios recientes',
        error: 'Error al cargar medios',
        new: 'Nuevo',
        minutes: 'min',
        play: 'Reproducir',
        pause: 'Pausa',
        stop: 'Detener',
        nothing_playing: 'Nada sonando',
        entity_not_found: 'Entidad no encontrada',
        rewinding: 'REBOBINANDO',
        no_trailer: 'No hay tráiler disponible',

        // Editor
        'editor.entity': 'Entidad',
        'editor.title': 'Título',
        'editor.show_title': 'Mostrar título',
        'editor.show_year': 'Mostrar año',
        'editor.show_runtime': 'Mostrar duración',
        'editor.show_rating': 'Mostrar clasificación',
        'editor.show_genres': 'Mostrar género',
        'editor.show_client': 'Mostrar cliente Jellyfin',
        'editor.show_background': 'Mostrar fondo',
        'editor.show_media_type_badge': 'Mostrar insignia de tipo de medio',
        'editor.show_watched_status': 'Mostrar estado de visualización',
        'editor.show_date_added': 'Mostrar fecha de adición',
        'editor.show_description': 'Mostrar descripción',
        'editor.layout': 'Diseño',
        'editor.layout_carousel': 'Carrusel',
        'editor.layout_grid': 'Cuadrícula',
        'editor.layout_list': 'Lista',
        'editor.media_type': 'Tipo de medio',
        'editor.media_type_both': 'Películas y Series',
        'editor.media_type_movies': 'Solo películas',
        'editor.media_type_series': 'Solo series',
        'editor.media_type_next_up': 'A continuación',
        'editor.items_per_page': 'Elementos por página',
        'editor.max_pages': 'Máx. páginas (0 = sin límite)',
        'editor.auto_swipe': 'Deslizamiento automático (seg, 0 = apagado)',
        'editor.new_badge_days': 'Días de insignia nueva (0 = apagado)',
        'editor.click_action': 'Pulsación corta (Clic)',
        'editor.hold_action': 'Pulsación larga (Mantener)',
        'editor.action_jellyfin': 'Abrir en Jellyfin',
        'editor.action_cast': 'Cast a Chromecast',
        'editor.action_more_info': 'Más información',
        'editor.action_trailer': 'Ver tráiler',
        'editor.action_none': 'Ninguna acción',
        'editor.default_cast_device': 'Dispositivo Cast predeterminado',
        'editor.show_now_playing_overlay': 'Superposición "Reproduciendo"',
        'editor.metadata_position': 'Posición de metadatos',
        'editor.metadata_below': 'Debajo',
        'editor.metadata_above': 'Arriba',
        'editor.sort_order': 'Orden de clasificación',
        'editor.sort_date_added_desc': 'Fecha de adición (Más reciente)',
        'editor.sort_date_added_asc': 'Fecha de adición (Más antiguo)',
        'editor.sort_title_asc': 'Título (A-Z)',
        'editor.sort_title_desc': 'Título (Z-A)',
        'editor.sort_year_desc': 'Año (Más reciente)',
        'editor.sort_year_asc': 'Año (Más antiguo)',
        'editor.sort_last_played_desc': 'Última reproducción (Más reciente)',
        'editor.sort_last_played_asc': 'Última reproducción (Más antiguo)',
        'editor.enable_pagination': 'Habilitar paginación',
        'editor.show_pagination_dots': 'Mostrar puntos de paginación',
        'editor.filter_watch_status': 'Filtrar estado de visualización',
        'editor.filter_all': 'Todos',
        'editor.filter_unwatched': 'No vistos',
        'editor.filter_watched': 'Vistos',
        'editor.filter_favorites': 'Filtrar favoritos',
        'editor.filter_new_items': 'Filtrar elementos nuevos',
        'editor.columns': 'Columnas',
        'editor.rows': 'Filas',
        'editor.now_playing_sensor': 'Sensor de reproducción actual',
        'editor.auto': 'Auto',
    },
    it: {
        loading: 'Caricamento…',
        no_media: 'Nessun media recente trovato',
        error: 'Errore nel caricamento dei media',
        new: 'Nuovo',
        minutes: 'min',
        play: 'Riproduci',
        pause: 'Pausa',
        stop: 'Stop',
        nothing_playing: 'Niente in riproduzione',
        entity_not_found: 'Entità non trovata',
        rewinding: 'RIAVVOLGIMENTO',
        no_trailer: 'Nessun trailer disponibile',

        // Editor
        'editor.entity': 'Entità',
        'editor.title': 'Titolo',
        'editor.show_title': 'Mostra titolo',
        'editor.show_year': 'Mostra anno',
        'editor.show_runtime': 'Mostra durata',
        'editor.show_rating': 'Mostra valutazione',
        'editor.show_genres': 'Mostra genere',
        'editor.show_client': 'Mostra client Jellyfin',
        'editor.show_background': 'Mostra sfondo',
        'editor.show_media_type_badge': 'Mostra badge tipo media',
        'editor.show_watched_status': 'Mostra stato guardato',
        'editor.show_date_added': 'Mostra data aggiunta',
        'editor.show_description': 'Mostra descrizione',
        'editor.layout': 'Layout',
        'editor.layout_carousel': 'Carosello',
        'editor.layout_grid': 'Griglia',
        'editor.layout_list': 'Elenco',
        'editor.media_type': 'Tipo di media',
        'editor.media_type_both': 'Film e Serie TV',
        'editor.media_type_movies': 'Solo Film',
        'editor.media_type_series': 'Solo Serie TV',
        'editor.media_type_next_up': 'In coda',
        'editor.items_per_page': 'Elementi per pagina',
        'editor.max_pages': 'Max pagine (0 = nessun limite)',
        'editor.auto_swipe': 'Scorrimento automatico (sec, 0 = spento)',
        'editor.new_badge_days': 'Giorni badge nuovo (0 = spento)',
        'editor.click_action': 'Pressione breve (Click)',
        'editor.hold_action': 'Pressione lunga (Tieni premuto)',
        'editor.action_jellyfin': 'Apri in Jellyfin',
        'editor.action_cast': 'Cast su Chromecast',
        'editor.action_more_info': 'Più informazioni',
        'editor.action_trailer': 'Guarda il trailer',
        'editor.action_none': 'Nessuna azione',
        'editor.default_cast_device': 'Dispositivo Cast predefinito',
        'editor.show_now_playing_overlay': 'Overlay "In riproduzione"',
        'editor.metadata_position': 'Posizione metadati',
        'editor.metadata_below': 'Sotto',
        'editor.metadata_above': 'Sopra',
        'editor.sort_order': 'Ordinamento',
        'editor.sort_date_added_desc': 'Data aggiunta (Più recente)',
        'editor.sort_date_added_asc': 'Data aggiunta (Meno recente)',
        'editor.sort_title_asc': 'Titolo (A-Z)',
        'editor.sort_title_desc': 'Titolo (Z-A)',
        'editor.sort_year_desc': 'Anno (Più recente)',
        'editor.sort_year_asc': 'Anno (Meno recente)',
        'editor.sort_last_played_desc': 'Ultima riproduzione (Più recente)',
        'editor.sort_last_played_asc': 'Ultima riproduzione (Meno recente)',
        'editor.enable_pagination': 'Abilita impaginazione',
        'editor.show_pagination_dots': 'Mostra punti impaginazione',
        'editor.filter_watch_status': 'Filtra stato guardato',
        'editor.filter_all': 'Tutti',
        'editor.filter_unwatched': 'Non guardati',
        'editor.filter_watched': 'Guardati',
        'editor.filter_favorites': 'Filtra preferiti',
        'editor.filter_new_items': 'Filtra nuovi elementi',
        'editor.columns': 'Colonne',
        'editor.rows': 'Righe',
        'editor.now_playing_sensor': 'Sensore in riproduzione',
        'editor.auto': 'Auto',
    },
    nl: {
        loading: 'Laden…',
        no_media: 'Geen recente media gevonden',
        error: 'Fout bij laden media',
        new: 'Nieuw',
        minutes: 'min',
        play: 'Afspelen',
        pause: 'Pauze',
        stop: 'Stop',
        nothing_playing: 'Niets aan het spelen',
        entity_not_found: 'Entiteit niet gevonden',
        rewinding: 'TERUGSPOELEN',
        no_trailer: 'Geen trailer beschikbaar',

        // Editor
        'editor.entity': 'Entiteit',
        'editor.title': 'Titel',
        'editor.show_title': 'Titel tonen',
        'editor.show_year': 'Jaar tonen',
        'editor.show_runtime': 'Duur tonen',
        'editor.show_rating': 'Beoordeling tonen',
        'editor.show_genres': 'Genre tonen',
        'editor.show_client': 'Jellyfin-client tonen',
        'editor.show_background': 'Achtergrond tonen',
        'editor.show_media_type_badge': 'Mediatype-badge tonen',
        'editor.show_watched_status': 'Bekeken-status tonen',
        'editor.show_date_added': 'Datum toegevoegd tonen',
        'editor.show_description': 'Beschrijving tonen',
        'editor.layout': 'Indeling',
        'editor.layout_carousel': 'Carrousel',
        'editor.layout_grid': 'Raster',
        'editor.layout_list': 'Lijst',
        'editor.media_type': 'Mediatype',
        'editor.media_type_both': 'Films & Series',
        'editor.media_type_movies': 'Alleen films',
        'editor.media_type_series': 'Alleen series',
        'editor.media_type_next_up': 'Volgende',
        'editor.items_per_page': 'Items per pagina',
        'editor.max_pages': 'Max. pagina\'s (0 = geen limiet)',
        'editor.auto_swipe': 'Auto-swipe (sec, 0 = uit)',
        'editor.new_badge_days': 'Nieuw-badge dagen',
        'editor.click_action': 'Kort drukken (Klik)',
        'editor.hold_action': 'Lang drukken (Ingedrukt houden)',
        'editor.action_jellyfin': 'Open in Jellyfin',
        'editor.action_cast': 'Casten naar Chromecast',
        'editor.action_more_info': 'Meer informatie',
        'editor.action_trailer': 'Bekijk trailer',
        'editor.action_none': 'Geen actie',
        'editor.default_cast_device': 'Standaard Cast-apparaat',
        'editor.show_now_playing_overlay': '"Nu aan het spelen"-overlay',
        'editor.metadata_position': 'Positie metadata',
        'editor.metadata_below': 'Onder',
        'editor.metadata_above': 'Boven',
        'editor.sort_order': 'Sorteervolgorde',
        'editor.sort_date_added_desc': 'Datum toegevoegd (Nieuwste)',
        'editor.sort_date_added_asc': 'Datum toegevoegd (Oudste)',
        'editor.sort_title_asc': 'Titel (A-Z)',
        'editor.sort_title_desc': 'Titel (Z-A)',
        'editor.sort_year_desc': 'Jaar (Nieuwste)',
        'editor.sort_year_asc': 'Jaar (Oudste)',
        'editor.sort_last_played_desc': 'Laatst gespeeld (Nieuwste)',
        'editor.sort_last_played_asc': 'Laatst gespeeld (Oudste)',
        'editor.enable_pagination': 'Paginering inschakelen',
        'editor.show_pagination_dots': 'Paginering-stippen tonen',
        'editor.filter_watch_status': 'Kijkstatus filteren',
        'editor.filter_all': 'Alles',
        'editor.filter_unwatched': 'Onbekeken',
        'editor.filter_watched': 'Bekeken',
        'editor.filter_favorites': 'Favorieten filteren',
        'editor.filter_new_items': 'Nieuwe items filteren',
        'editor.columns': 'Kolommen',
        'editor.rows': 'Rijen',
        'editor.now_playing_sensor': 'Sensor "Nu aan het spelen"',
        'editor.auto': 'Auto',
    },
};

/**
 * Get localized string
 * @param language - Language code (e.g., 'en', 'de')
 * @param key - Translation key
 * @returns Translated string or key if not found
 */
export function localize(language: string, key: string): string {
    const lang = language.split('-')[0].toLowerCase();

    // Try exact language
    if (translations[lang]?.[key]) {
        return translations[lang][key];
    }

    // Fallback to English
    if (translations.en?.[key]) {
        return translations.en[key];
    }

    // Return key if nothing found
    return key;
}
