/**
 * Localization helper for JellyHA Library Card
 */

const translations: Record<string, Record<string, string>> = {
    en: {
        loading: 'Loading…',
        no_media: 'No recent media found',
        error: 'Error loading media',
        new: 'New',
        minutes: 'min',
        play: 'Play',
        pause: 'Pause',
        stop: 'Stop',
        previous: 'Previous',
        next: 'Next',
        nothing_playing: 'Nothing is currently playing',
        entity_not_found: 'Entity not found',
        rewinding: 'REWINDING',
        no_trailer: 'No trailer available',

        // Editor
        'editor.entity': 'Entity',
        'editor.title': 'Title',
        'editor.show_title': 'Show Title',
        'editor.show_subtitle': 'Show Artist / Series',
        'editor.show_year': 'Show Year',
        'editor.show_runtime': 'Show Runtime',
        'editor.show_rating': 'Show Rating',
        'editor.show_genres': 'Show Genre',
        'editor.show_client': 'Show Jellyfin Client',
        'editor.show_user': 'Show User',
        'editor.show_time': 'Show Elapsed / Remaining Time',
        'editor.show_background': 'Show Background',
        'editor.use_series_image': 'Use Series Cover Image',
        'editor.show_media_type_badge': 'Show Media Type Badge',
        'editor.show_watched_status': 'Show Watched Status',
        'editor.show_date_added': 'Show Date Added',
        'editor.show_description': 'Show Description',
        'editor.layout': 'Layout',
        'editor.layout_carousel': 'Carousel',
        'editor.layout_grid': 'Grid',
        'editor.layout_list': 'List',
        'editor.media_type': 'Media Type',
        'editor.media_type_both': 'Movies & TV Shows',
        'editor.media_type_movies': 'Movies Only',
        'editor.media_type_series': 'TV Shows Only',
        'editor.media_type_next_up': 'Next Up',
        'editor.tv_content': 'TV Content',
        'editor.tv_content_series': 'Shows / Series',
        'editor.tv_content_episodes': 'Episodes',
        'editor.items_per_page': 'Items Per Page',
        'editor.max_pages': 'Max Pages (0 = no limit)',
        'editor.auto_swipe': 'Auto Swipe (sec, 0 = off)',
        'editor.new_badge_days': 'New Badge Days (0 = off)',
        'editor.click_action': 'Single Tap (Click)',
        'editor.hold_action': 'Long Press (Hold)',
        'editor.double_tap_action': 'Double Tap',
        'editor.action_jellyfin': 'Open in Jellyfin',
        'editor.action_cast': 'Cast to Chromecast',
        'editor.action_more_info': 'More Information',
        'editor.action_trailer': 'Watch Trailer',
        'editor.action_none': 'No Action',
        'editor.action_call_service': 'Run Script',
        'editor.service_to_call': 'Script',
        'editor.service_data': 'Service Data (Optional JSON, e.g. {"player":"tv"})',
        'editor.default_cast_device': 'Default Cast Device',
        'editor.show_now_playing_overlay': 'Show "Now Playing" Overlay on Posters',
        'editor.metadata_position': 'Metadata Position',
        'editor.metadata_below': 'Below',
        'editor.metadata_above': 'Above',
        'editor.sort_order': 'Sort Order',
        'editor.sort_date_added_desc': 'Date Added (Newest First)',
        'editor.sort_date_added_asc': 'Date Added (Oldest First)',
        'editor.sort_title_asc': 'Title (A-Z)',
        'editor.sort_title_desc': 'Title (Z-A)',
        'editor.sort_year_desc': 'Year (Newest First)',
        'editor.sort_year_asc': 'Year (Oldest First)',
        'editor.sort_last_played_desc': 'Last Played (Newest First)',
        'editor.sort_last_played_asc': 'Last Played (Oldest First)',
        'editor.enable_pagination': 'Enable Pagination',
        'editor.show_pagination_dots': 'Show Pagination Dots',
        'editor.filter_watch_status': 'Filter Watch Status',
        'editor.filter_all': 'All',
        'editor.filter_unwatched': 'Unwatched',
        'editor.filter_watched': 'Watched',
        'editor.filter_favorites': 'Filter Favorites',
        'editor.filter_new_items': 'Filter New Items',
        'editor.columns': 'Columns',
        'editor.rows': 'Rows',
        'editor.media_player': 'Media Player',
        'editor.now_playing_sensor': 'Media Player',
        'editor.auto': 'Auto',
        'editor.show_search': 'Show Search Bar',
        'editor.show_controls': 'Show Playback Controls',
        'editor.horizontal_alignment': 'Carousel Alignment',
        'editor.alignment_center': 'Center',
        'editor.alignment_left': 'Left',
        'search.placeholder_title': 'Search Title',
        'search.placeholder_genre': 'Genre',
        'search.all_genres': 'All Genres',
    },
    de: {
        loading: 'Laden…',
        no_media: 'Keine Medien gefunden',
        error: 'Fehler beim Laden',
        new: 'Neu',
        minutes: 'Min',
        play: 'Abspielen',
        pause: 'Pause',
        stop: 'Stopp',
        previous: 'Zurück',
        next: 'Weiter',
        nothing_playing: 'Nichts wird abgespielt',
        entity_not_found: 'Entität nicht gefunden',
        rewinding: 'SPULEN',
        no_trailer: 'Kein Trailer verfügbar',

        // Editor
        'editor.entity': 'Entität',
        'editor.title': 'Titel',
        'editor.show_title': 'Titel anzeigen',
        'editor.show_subtitle': 'Interpret / Serie anzeigen',
        'editor.show_year': 'Jahr anzeigen',
        'editor.show_runtime': 'Laufzeit anzeigen',
        'editor.show_rating': 'Bewertung anzeigen',
        'editor.show_genres': 'Genre anzeigen',
        'editor.show_client': 'Jellyfin-Client anzeigen',
        'editor.show_user': 'Benutzer anzeigen',
        'editor.show_time': 'Verstrichene / Restzeit anzeigen',
        'editor.show_background': 'Hintergrund anzeigen',
        'editor.use_series_image': 'Serien-Cover verwenden',
        'editor.show_media_type_badge': 'Medientyp-Abzeichen anzeigen',
        'editor.show_watched_status': 'Gesehen-Status anzeigen',
        'editor.show_date_added': 'Hinzugefügt am anzeigen',
        'editor.show_description': 'Beschreibung anzeigen',
        'editor.layout': 'Layout',
        'editor.layout_carousel': 'Karussell',
        'editor.layout_grid': 'Raster',
        'editor.layout_list': 'Liste',
        'editor.media_type': 'Medientyp',
        'editor.media_type_both': 'Filme & Serien',
        'editor.media_type_movies': 'Nur Filme',
        'editor.media_type_series': 'Nur Serien',
        'editor.media_type_next_up': 'Als Nächstes',
        'editor.tv_content': 'TV-Inhalt',
        'editor.tv_content_series': 'Shows / Serien',
        'editor.tv_content_episodes': 'Episoden',
        'editor.items_per_page': 'Elemente pro Seite',
        'editor.max_pages': 'Max. Seiten (0 = kein Limit)',
        'editor.auto_swipe': 'Auto-Swipe (Sek., 0 = aus)',
        'editor.new_badge_days': 'Badge "Neu" Tage (0 = aus)',
        'editor.click_action': 'Kurz drücken (Klick)',
        'editor.hold_action': 'Lang drücken (Halten)',
        'editor.double_tap_action': 'Doppeltippen',
        'editor.action_jellyfin': 'In Jellyfin öffnen',
        'editor.action_cast': 'An Chromecast senden',
        'editor.action_more_info': 'Mehr Informationen',
        'editor.action_trailer': 'Trailer ansehen',
        'editor.action_none': 'Keine Aktion',
        'editor.action_call_service': 'Skript ausführen',
        'editor.service_to_call': 'Skript',
        'editor.service_data': 'Servicedaten (Optional JSON, z.B. {"player":"tv"})',
        'editor.default_cast_device': 'Standard-Chromecast-Gerät',
        'editor.show_now_playing_overlay': '"Jetzt läuft"-Overlay anzeigen',
        'editor.metadata_position': 'Metadaten-Position',
        'editor.metadata_below': 'Darunter',
        'editor.metadata_above': 'Darüber',
        'editor.sort_order': 'Sortierung',
        'editor.sort_date_added_desc': 'Hinzugefügt (Neueste zuerst)',
        'editor.sort_date_added_asc': 'Hinzugefügt (Älteste zuerst)',
        'editor.sort_title_asc': 'Titel (A-Z)',
        'editor.sort_title_desc': 'Titel (Z-A)',
        'editor.sort_year_desc': 'Jahr (Neueste zuerst)',
        'editor.sort_year_asc': 'Jahr (Älteste zuerst)',
        'editor.sort_last_played_desc': 'Zuletzt gespielt (Neueste zuerst)',
        'editor.sort_last_played_asc': 'Zuletzt gespielt (Älteste zuerst)',
        'editor.enable_pagination': 'Seitennummerierung aktivieren',
        'editor.show_pagination_dots': 'Paginierungspunkte anzeigen',
        'editor.filter_watch_status': 'Gesehen-Status filtern',
        'editor.filter_all': 'Alle',
        'editor.filter_unwatched': 'Ungesehen',
        'editor.filter_watched': 'Gesehen',
        'editor.filter_favorites': 'Favoriten filtern',
        'editor.filter_new_items': 'Neue Elemente filtern',
        'editor.columns': 'Spalten',
        'editor.rows': 'Zeilen',
        'editor.media_player': 'Medienplayer',
        'editor.now_playing_sensor': 'Medienplayer',
        'editor.auto': 'Automatisch',
        'editor.show_search': 'Suchleiste anzeigen',
        'editor.show_controls': 'Wiedergabesteuerung anzeigen',
        'editor.horizontal_alignment': 'Karussell-Ausrichtung',
        'editor.alignment_center': 'Zentriert',
        'editor.alignment_left': 'Links',
        'search.placeholder_title': 'Titel suchen',
        'search.placeholder_genre': 'Genre',
        'search.all_genres': 'Alle Genres',
    },
    fr: {
        loading: 'Chargement…',
        no_media: 'Aucun média récent trouvé',
        error: 'Erreur de chargement des médias',
        new: 'Nouveau',
        minutes: 'min',
        play: 'Lire',
        pause: 'Pause',
        stop: 'Arrêt',
        previous: 'Précédent',
        next: 'Suivant',
        nothing_playing: 'Rien en lecture',
        entity_not_found: 'Entité non trouvée',
        rewinding: 'BOBINAGE',
        no_trailer: 'Aucune bande-annonce disponible',

        // Editor
        'editor.entity': 'Entité',
        'editor.title': 'Titre',
        'editor.show_title': 'Afficher le titre',
        'editor.show_subtitle': 'Afficher l\'artiste / la série',
        'editor.show_year': 'Afficher l\'année',
        'editor.show_runtime': 'Afficher la durée',
        'editor.show_rating': 'Afficher la note',
        'editor.show_genres': 'Afficher le genre',
        'editor.show_client': 'Afficher le client Jellyfin',
        'editor.show_user': 'Afficher l\'utilisateur',
        'editor.show_time': 'Afficher le temps écoulé / restant',
        'editor.show_background': 'Afficher l\'arrière-plan',
        'editor.use_series_image': 'Utiliser l\'image de couverture de la série',
        'editor.show_media_type_badge': 'Afficher le badge de type de média',
        'editor.show_watched_status': 'Afficher le statut de visionnage',
        'editor.show_date_added': 'Afficher la date d\'ajout',
        'editor.show_description': 'Afficher la description',
        'editor.layout': 'Mise en page',
        'editor.layout_carousel': 'Carrousel',
        'editor.layout_grid': 'Grille',
        'editor.layout_list': 'Liste',
        'editor.media_type': 'Type de média',
        'editor.media_type_both': 'Films et séries',
        'editor.media_type_movies': 'Films seulement',
        'editor.media_type_series': 'Séries seulement',
        'editor.media_type_next_up': 'À suivre',
        'editor.tv_content': 'Contenu TV',
        'editor.tv_content_series': 'Émissions / Séries',
        'editor.tv_content_episodes': 'Épisodes',
        'editor.items_per_page': 'Éléments par page',
        'editor.max_pages': 'Pages max (0 = illimité)',
        'editor.auto_swipe': 'Défilement auto (sec, 0 = désactivé)',
        'editor.new_badge_days': 'Jours badge nouveau (0 = désactivé)',
        'editor.click_action': 'Appui court (Clic)',
        'editor.hold_action': 'Appui long (Maintenir)',
        'editor.double_tap_action': 'Double appui',
        'editor.action_jellyfin': 'Ouvrir dans Jellyfin',
        'editor.action_cast': 'Caster sur Chromecast',
        'editor.action_more_info': 'Plus d\'informations',
        'editor.action_trailer': 'Voir la bande-annonce',
        'editor.action_none': 'Aucune action',
        'editor.action_call_service': 'Exécuter un script',
        'editor.service_to_call': 'Script',
        'editor.service_data': 'Données du service (JSON optionnel, ex: {"player":"tv"})',
        'editor.default_cast_device': 'Appareil Cast par défaut',
        'editor.show_now_playing_overlay': 'Superposition "En lecture"',
        'editor.metadata_position': 'Position des métadonnées',
        'editor.metadata_below': 'Dessous',
        'editor.metadata_above': 'Dessus',
        'editor.sort_order': 'Ordre de tri',
        'editor.sort_date_added_desc': 'Date d\'ajout (Plus récent)',
        'editor.sort_date_added_asc': 'Date d\'ajout (Plus ancien)',
        'editor.sort_title_asc': 'Titre (A-Z)',
        'editor.sort_title_desc': 'Titre (Z-A)',
        'editor.sort_year_desc': 'Année (Plus récent)',
        'editor.sort_year_asc': 'Année (Plus ancien)',
        'editor.sort_last_played_desc': 'Dernière lecture (Plus récent)',
        'editor.sort_last_played_asc': 'Dernière lecture (Plus ancien)',
        'editor.enable_pagination': 'Activer la pagination',
        'editor.show_pagination_dots': 'Afficher les points de pagination',
        'editor.filter_watch_status': 'Filtrer le statut de visionnage',
        'editor.filter_all': 'Tous',
        'editor.filter_unwatched': 'Non vus',
        'editor.filter_watched': 'Vus',
        'editor.filter_favorites': 'Filtrer les favoris',
        'editor.filter_new_items': 'Filtrer les nouveaux éléments',
        'editor.columns': 'Colonnes',
        'editor.rows': 'Lignes',
        'editor.media_player': 'Lecteur multimédia',
        'editor.now_playing_sensor': 'Lecteur multimédia',
        'editor.auto': 'Auto',
        'editor.show_search': 'Afficher la barre de recherche',
        'editor.show_controls': 'Afficher les commandes de lecture',
        'editor.horizontal_alignment': 'Alignement du carrousel',
        'editor.alignment_center': 'Centré',
        'editor.alignment_left': 'Gauche',
        'search.placeholder_title': 'Rechercher un titre',
        'search.placeholder_genre': 'Genre',
        'search.all_genres': 'Tous les genres',
    },
    es: {
        loading: 'Cargando…',
        no_media: 'No se encontraron medios recientes',
        error: 'Error al cargar medios',
        new: 'Nuevo',
        minutes: 'min',
        play: 'Reproducir',
        pause: 'Pausa',
        stop: 'Detener',
        previous: 'Anterior',
        next: 'Siguiente',
        nothing_playing: 'Nada sonando',
        entity_not_found: 'Entidad no encontrada',
        rewinding: 'REBOBINANDO',
        no_trailer: 'No hay tráiler disponible',

        // Editor
        'editor.entity': 'Entidad',
        'editor.title': 'Título',
        'editor.show_title': 'Mostrar título',
        'editor.show_subtitle': 'Mostrar artista / serie',
        'editor.show_year': 'Mostrar año',
        'editor.show_runtime': 'Mostrar duración',
        'editor.show_rating': 'Mostrar clasificación',
        'editor.show_genres': 'Mostrar género',
        'editor.show_client': 'Mostrar cliente Jellyfin',
        'editor.show_user': 'Mostrar usuario',
        'editor.show_time': 'Mostrar tiempo transcurrido / restante',
        'editor.show_background': 'Mostrar fondo',
        'editor.use_series_image': 'Usar imagen de portada de serie',
        'editor.show_media_type_badge': 'Mostrar insignia de tipo de medio',
        'editor.show_watched_status': 'Mostrar estado de visualización',
        'editor.show_date_added': 'Mostrar fecha de adición',
        'editor.show_description': 'Mostrar descripción',
        'editor.layout': 'Diseño',
        'editor.layout_carousel': 'Carrusel',
        'editor.layout_grid': 'Cuadrícula',
        'editor.layout_list': 'Lista',
        'editor.media_type': 'Tipo de medio',
        'editor.media_type_both': 'Películas y Series',
        'editor.media_type_movies': 'Solo películas',
        'editor.media_type_series': 'Solo series',
        'editor.media_type_next_up': 'A continuación',
        'editor.tv_content': 'Contenido de TV',
        'editor.tv_content_series': 'Programas / Series',
        'editor.tv_content_episodes': 'Episodios',
        'editor.items_per_page': 'Elementos por página',
        'editor.max_pages': 'Máx. páginas (0 = sin límite)',
        'editor.auto_swipe': 'Deslizamiento automático (seg, 0 = apagado)',
        'editor.new_badge_days': 'Días de insignia nueva (0 = apagado)',
        'editor.click_action': 'Pulsación corta (Clic)',
        'editor.hold_action': 'Pulsación larga (Mantener)',
        'editor.double_tap_action': 'Doble toque',
        'editor.action_jellyfin': 'Abrir en Jellyfin',
        'editor.action_cast': 'Cast a Chromecast',
        'editor.action_more_info': 'Más información',
        'editor.action_trailer': 'Ver tráiler',
        'editor.action_none': 'Ninguna acción',
        'editor.action_call_service': 'Ejecutar script',
        'editor.service_to_call': 'Script',
        'editor.service_data': 'Datos del servicio (JSON opcional, ej. {"player":"tv"})',
        'editor.default_cast_device': 'Dispositivo Cast predeterminado',
        'editor.show_now_playing_overlay': 'Superposición "Reproduciendo"',
        'editor.metadata_position': 'Posición de metadatos',
        'editor.metadata_below': 'Debajo',
        'editor.metadata_above': 'Arriba',
        'editor.sort_order': 'Orden de clasificación',
        'editor.sort_date_added_desc': 'Fecha de adición (Más reciente)',
        'editor.sort_date_added_asc': 'Fecha de adición (Más antiguo)',
        'editor.sort_title_asc': 'Título (A-Z)',
        'editor.sort_title_desc': 'Título (Z-A)',
        'editor.sort_year_desc': 'Año (Más reciente)',
        'editor.sort_year_asc': 'Año (Más antiguo)',
        'editor.sort_last_played_desc': 'Última reproducción (Más reciente)',
        'editor.sort_last_played_asc': 'Última reproducción (Más antiguo)',
        'editor.enable_pagination': 'Habilitar paginación',
        'editor.show_pagination_dots': 'Mostrar puntos de paginación',
        'editor.filter_watch_status': 'Filtrar estado de visualización',
        'editor.filter_all': 'Todos',
        'editor.filter_unwatched': 'No vistos',
        'editor.filter_watched': 'Vistos',
        'editor.filter_favorites': 'Filtrar favoritos',
        'editor.filter_new_items': 'Filtrar elementos nuevos',
        'editor.columns': 'Columnas',
        'editor.rows': 'Filas',
        'editor.media_player': 'Reproductor multimedia',
        'editor.now_playing_sensor': 'Reproductor multimedia',
        'editor.auto': 'Auto',
        'editor.show_search': 'Mostrar barra de búsqueda',
        'editor.show_controls': 'Mostrar controles de reproducción',
        'editor.horizontal_alignment': 'Alineación del carrusel',
        'editor.alignment_center': 'Centrado',
        'editor.alignment_left': 'Izquierda',
        'search.placeholder_title': 'Buscar título',
        'search.placeholder_genre': 'Género',
        'search.all_genres': 'Todos los géneros',
    },
    it: {
        loading: 'Caricamento…',
        no_media: 'Nessun media recente trovato',
        error: 'Errore nel caricamento dei media',
        new: 'Nuovo',
        minutes: 'min',
        play: 'Riproduci',
        pause: 'Pausa',
        stop: 'Stop',
        previous: 'Precedente',
        next: 'Successivo',
        nothing_playing: 'Niente in riproduzione',
        entity_not_found: 'Entità non trovata',
        rewinding: 'RIAVVOLGIMENTO',
        no_trailer: 'Nessun trailer disponibile',

        // Editor
        'editor.entity': 'Entità',
        'editor.title': 'Titolo',
        'editor.show_title': 'Mostra titolo',
        'editor.show_subtitle': 'Mostra artista / serie',
        'editor.show_year': 'Mostra anno',
        'editor.show_runtime': 'Mostra durata',
        'editor.show_rating': 'Mostra valutazione',
        'editor.show_genres': 'Mostra genere',
        'editor.show_client': 'Mostra client Jellyfin',
        'editor.show_user': 'Mostra utente',
        'editor.show_time': 'Mostra tempo trascorso / rimanente',
        'editor.show_background': 'Mostra sfondo',
        'editor.use_series_image': 'Usa immagine copertina serie',
        'editor.show_media_type_badge': 'Mostra badge tipo media',
        'editor.show_watched_status': 'Mostra stato guardato',
        'editor.show_date_added': 'Mostra data aggiunta',
        'editor.show_description': 'Mostra descrizione',
        'editor.layout': 'Layout',
        'editor.layout_carousel': 'Carosello',
        'editor.layout_grid': 'Griglia',
        'editor.layout_list': 'Elenco',
        'editor.media_type': 'Tipo di media',
        'editor.media_type_both': 'Film e Serie TV',
        'editor.media_type_movies': 'Solo Film',
        'editor.media_type_series': 'Solo Serie TV',
        'editor.media_type_next_up': 'In coda',
        'editor.tv_content': 'Contenuto TV',
        'editor.tv_content_series': 'Programmi / Serie TV',
        'editor.tv_content_episodes': 'Episodi',
        'editor.items_per_page': 'Elementi per pagina',
        'editor.max_pages': 'Max pagine (0 = nessun limite)',
        'editor.auto_swipe': 'Scorrimento automatico (sec, 0 = spento)',
        'editor.new_badge_days': 'Giorni badge nuovo (0 = spento)',
        'editor.click_action': 'Pressione breve (Click)',
        'editor.hold_action': 'Pressione lunga (Tieni premuto)',
        'editor.double_tap_action': 'Doppio tocco',
        'editor.action_jellyfin': 'Apri in Jellyfin',
        'editor.action_cast': 'Cast su Chromecast',
        'editor.action_more_info': 'Più informazioni',
        'editor.action_trailer': 'Guarda il trailer',
        'editor.action_none': 'Nessuna azione',
        'editor.action_call_service': 'Esegui script',
        'editor.service_to_call': 'Script',
        'editor.service_data': 'Dati del servizio (JSON opzionale, es. {"player":"tv"})',
        'editor.default_cast_device': 'Dispositivo Cast predefinito',
        'editor.show_now_playing_overlay': 'Overlay "In riproduzione"',
        'editor.metadata_position': 'Posizione metadati',
        'editor.metadata_below': 'Sotto',
        'editor.metadata_above': 'Sopra',
        'editor.sort_order': 'Ordinamento',
        'editor.sort_date_added_desc': 'Data aggiunta (Più recente)',
        'editor.sort_date_added_asc': 'Data aggiunta (Meno recente)',
        'editor.sort_title_asc': 'Titolo (A-Z)',
        'editor.sort_title_desc': 'Titolo (Z-A)',
        'editor.sort_year_desc': 'Anno (Più recente)',
        'editor.sort_year_asc': 'Anno (Meno recente)',
        'editor.sort_last_played_desc': 'Ultima riproduzione (Più recente)',
        'editor.sort_last_played_asc': 'Ultima riproduzione (Meno recente)',
        'editor.enable_pagination': 'Abilita impaginazione',
        'editor.show_pagination_dots': 'Mostra punti impaginazione',
        'editor.filter_watch_status': 'Filtra stato guardato',
        'editor.filter_all': 'Tutti',
        'editor.filter_unwatched': 'Non guardati',
        'editor.filter_watched': 'Guardati',
        'editor.filter_favorites': 'Filtra preferiti',
        'editor.filter_new_items': 'Filtra nuovi elementi',
        'editor.columns': 'Colonne',
        'editor.rows': 'Righe',
        'editor.media_player': 'Lettore multimediale',
        'editor.now_playing_sensor': 'Lettore multimediale',
        'editor.auto': 'Auto',
        'editor.show_search': 'Mostra barra di ricerca',
        'editor.show_controls': 'Mostra controlli di riproduzione',
        'editor.horizontal_alignment': 'Allineamento carosello',
        'editor.alignment_center': 'Centro',
        'editor.alignment_left': 'Sinistra',
        'search.placeholder_title': 'Cerca titolo',
        'search.placeholder_genre': 'Genere',
        'search.all_genres': 'Tutti i generi',
    },
    nl: {
        loading: 'Laden…',
        no_media: 'Geen recente media gevonden',
        error: 'Fout bij laden media',
        new: 'Nieuw',
        minutes: 'min',
        play: 'Afspelen',
        pause: 'Pauze',
        stop: 'Stop',
        previous: 'Vorige',
        next: 'Volgende',
        nothing_playing: 'Niets aan het spelen',
        entity_not_found: 'Entiteit niet gevonden',
        rewinding: 'TERUGSPOELEN',
        no_trailer: 'Geen trailer beschikbaar',

        // Editor
        'editor.entity': 'Entiteit',
        'editor.title': 'Titel',
        'editor.show_title': 'Titel tonen',
        'editor.show_subtitle': 'Artiest / serie tonen',
        'editor.show_year': 'Jaar tonen',
        'editor.show_runtime': 'Duur tonen',
        'editor.show_rating': 'Beoordeling tonen',
        'editor.show_genres': 'Genre tonen',
        'editor.show_client': 'Jellyfin-client tonen',
        'editor.show_user': 'Gebruiker tonen',
        'editor.show_time': 'Verstreken / resterende tijd tonen',
        'editor.show_background': 'Achtergrond tonen',
        'editor.use_series_image': 'Gebruik serie-omslagafbeelding',
        'editor.show_media_type_badge': 'Mediatype-badge tonen',
        'editor.show_watched_status': 'Bekeken-status tonen',
        'editor.show_date_added': 'Datum toegevoegd tonen',
        'editor.show_description': 'Beschrijving tonen',
        'editor.layout': 'Indeling',
        'editor.layout_carousel': 'Carrousel',
        'editor.layout_grid': 'Raster',
        'editor.layout_list': 'Lijst',
        'editor.media_type': 'Mediatype',
        'editor.media_type_both': 'Films & Series',
        'editor.media_type_movies': 'Alleen films',
        'editor.media_type_series': 'Alleen series',
        'editor.media_type_next_up': 'Volgende',
        'editor.tv_content': 'TV-inhoud',
        'editor.tv_content_series': 'Shows / Series',
        'editor.tv_content_episodes': 'Afleveringen',
        'editor.items_per_page': 'Items per pagina',
        'editor.max_pages': 'Max. pagina\'s (0 = geen limiet)',
        'editor.auto_swipe': 'Auto-swipe (sec, 0 = uit)',
        'editor.new_badge_days': 'Dagen badge nieuw (0 = uit)',
        'editor.click_action': 'Kort indrukken (Klik)',
        'editor.hold_action': 'Lang indrukken (Vasthouden)',
        'editor.double_tap_action': 'Dubbel tikken',
        'editor.action_jellyfin': 'Open in Jellyfin',
        'editor.action_cast': 'Casten naar Chromecast',
        'editor.action_more_info': 'Meer informatie',
        'editor.action_trailer': 'Bekijk trailer',
        'editor.action_none': 'Geen actie',
        'editor.action_call_service': 'Script uitvoeren',
        'editor.service_to_call': 'Script',
        'editor.service_data': 'Servicegegevens (Optioneel JSON, bijv. {"player":"tv"})',
        'editor.default_cast_device': 'Standaard Cast-apparaat',
        'editor.show_now_playing_overlay': '"Nu aan het spelen"-overlay',
        'editor.metadata_position': 'Positie metadata',
        'editor.metadata_below': 'Onder',
        'editor.metadata_above': 'Boven',
        'editor.sort_order': 'Sorteervolgorde',
        'editor.sort_date_added_desc': 'Datum toegevoegd (Nieuwste)',
        'editor.sort_date_added_asc': 'Datum toegevoegd (Oudste)',
        'editor.sort_title_asc': 'Titel (A-Z)',
        'editor.sort_title_desc': 'Titel (Z-A)',
        'editor.sort_year_desc': 'Jaar (Nieuwste)',
        'editor.sort_year_asc': 'Jaar (Oudste)',
        'editor.sort_last_played_desc': 'Laatst gespeeld (Nieuwste)',
        'editor.sort_last_played_asc': 'Laatst gespeeld (Oudste)',
        'editor.enable_pagination': 'Paginering inschakelen',
        'editor.show_pagination_dots': 'Paginering-stippen tonen',
        'editor.filter_watch_status': 'Kijkstatus filteren',
        'editor.filter_all': 'Alles',
        'editor.filter_unwatched': 'Onbekeken',
        'editor.filter_watched': 'Bekeken',
        'editor.filter_favorites': 'Favorieten filteren',
        'editor.filter_new_items': 'Nieuwe items filteren',
        'editor.columns': 'Kolommen',
        'editor.rows': 'Rijen',
        'editor.media_player': 'Mediaspeler',
        'editor.now_playing_sensor': 'Mediaspeler',
        'editor.auto': 'Auto',
        'editor.show_search': 'Zoekbalk tonen',
        'editor.show_controls': 'Afspeelknoppen tonen',
        'editor.horizontal_alignment': 'Carrousel uitlijning',
        'editor.alignment_center': 'Midden',
        'editor.alignment_left': 'Links',
        'search.placeholder_title': 'Zoek titel',
        'search.placeholder_genre': 'Genre',
        'search.all_genres': 'Alle genres',
    },
    sl: {
        loading: 'Nalaganje…',
        no_media: 'Ni nedavnih medijev',
        error: 'Napaka pri nalaganju medijev',
        new: 'Novo',
        minutes: 'min',
        play: 'Predvajaj',
        pause: 'Premor',
        stop: 'Stop',
        previous: 'Prejšnji',
        next: 'Naslednji',
        nothing_playing: 'Nič se ne predvaja',
        entity_not_found: 'Entiteta ni najdena',
        rewinding: 'PREVIJANJE',
        no_trailer: 'Napovednik ni na voljo',

        // Editor
        'editor.entity': 'Entiteta',
        'editor.title': 'Naslov',
        'editor.show_title': 'Prikaži naslov',
        'editor.show_subtitle': 'Prikaži izvajalca / serijo',
        'editor.show_year': 'Prikaži leto',
        'editor.show_runtime': 'Prikaži trajanje',
        'editor.show_rating': 'Prikaži oceno',
        'editor.show_genres': 'Prikaži žanr',
        'editor.show_client': 'Prikaži Jellyfin odjemalec',
        'editor.show_user': 'Prikaži uporabnika',
        'editor.show_time': 'Prikaži pretečen / preostali čas',
        'editor.show_background': 'Prikaži ozadje',
        'editor.use_series_image': 'Uporabi sliko naslovnice serije',
        'editor.show_media_type_badge': 'Prikaži značko tipa medija',
        'editor.show_watched_status': 'Prikaži status ogleda',
        'editor.show_date_added': 'Prikaži datum dodajanja',
        'editor.show_description': 'Prikaži opis',
        'editor.layout': 'Postavitev',
        'editor.layout_carousel': 'Vrtiljak',
        'editor.layout_grid': 'Mreža',
        'editor.layout_list': 'Seznam',
        'editor.media_type': 'Tip medija',
        'editor.media_type_both': 'Filmi in serije',
        'editor.media_type_movies': 'Samo filmi',
        'editor.media_type_series': 'Samo serije',
        'editor.media_type_next_up': 'Naslednje',
        'editor.tv_content': 'TV vsebina',
        'editor.tv_content_series': 'Oddaje / Serije',
        'editor.tv_content_episodes': 'Epizode',
        'editor.items_per_page': 'Elementov na stran',
        'editor.max_pages': 'Max strani (0 = brez omejitve)',
        'editor.auto_swipe': 'Samodejno drsenje (sek, 0 = izklopljeno)',
        'editor.new_badge_days': 'Dnevi za značko Novo (0 = izklopljeno)',
        'editor.click_action': 'Kratek pritisk (Klik)',
        'editor.hold_action': 'Dolg pritisk (Drži)',
        'editor.double_tap_action': 'Dvojni dotik',
        'editor.action_jellyfin': 'Odpri v Jellyfin',
        'editor.action_cast': 'Predvajaj na Chromecast',
        'editor.action_more_info': 'Več informacij',
        'editor.action_trailer': 'Poglej napovednik',
        'editor.action_none': 'Brez akcije',
        'editor.action_call_service': 'Zaženi skript',
        'editor.service_to_call': 'Skript',
        'editor.service_data': 'Podatki servisa (Opcijski JSON, npr. {"player":"tv"})',
        'editor.default_cast_device': 'Privzeta Chromecast naprava',
        'editor.show_now_playing_overlay': 'Prikaži "Zdaj se predvaja" prekrivanje',
        'editor.metadata_position': 'Pozicija metapodatkov',
        'editor.metadata_below': 'Spodaj',
        'editor.metadata_above': 'Zgoraj',
        'editor.sort_order': 'Vrstni red',
        'editor.sort_date_added_desc': 'Datum dodajanja (Novejši naprej)',
        'editor.sort_date_added_asc': 'Datum dodajanja (Starejši naprej)',
        'editor.sort_title_asc': 'Naslov (A-Z)',
        'editor.sort_title_desc': 'Naslov (Z-A)',
        'editor.sort_year_desc': 'Leto (Novejši naprej)',
        'editor.sort_year_asc': 'Leto (Starejši naprej)',
        'editor.sort_last_played_desc': 'Zadnje predvajano (Novejši naprej)',
        'editor.sort_last_played_asc': 'Zadnje predvajano (Starejši naprej)',
        'editor.enable_pagination': 'Omogoči oštevilčevanje',
        'editor.show_pagination_dots': 'Prikaži pike oštevilčevanja',
        'editor.filter_watch_status': 'Filtriraj status ogleda',
        'editor.filter_all': 'Vse',
        'editor.filter_unwatched': 'Neogledano',
        'editor.filter_watched': 'Ogledano',
        'editor.filter_favorites': 'Filtriraj priljubljene',
        'editor.filter_new_items': 'Filtriraj nove elemente',
        'editor.columns': 'Stolpci',
        'editor.rows': 'Vrstice',
        'editor.media_player': 'Predvajalnik medijev',
        'editor.now_playing_sensor': 'Predvajalnik medijev',
        'editor.auto': 'Avtomatsko',
        'editor.show_search': 'Prikaži iskalno vrstico',
        'editor.show_controls': 'Prikaži kontrolnike za predvajanje',
        'editor.horizontal_alignment': 'Poravnava vrtiljaka',
        'editor.alignment_center': 'Na sredino',
        'editor.alignment_left': 'Levo',
        'search.placeholder_title': 'Išči naslov',
        'search.placeholder_genre': 'Žanr',
        'search.all_genres': 'Vsi žanri',

    },
    ru: {
        loading: 'Загрузка…',
        no_media: 'Недавние медиа не найдены',
        error: 'Ошибка загрузки медиа',
        new: 'Новое',
        minutes: 'мин',
        play: 'Воспроизвести',
        pause: 'Пауза',
        stop: 'Остановить',
        previous: 'Предыдущий',
        next: 'Следующий',
        nothing_playing: 'Ничего не воспроизводится',
        entity_not_found: 'Объект не найден',
        rewinding: 'ПЕРЕМОТКА',
        no_trailer: 'Трейлер недоступен',

        // Editor
        'editor.entity': 'Объект',
        'editor.title': 'Название',
        'editor.show_title': 'Показывать название',
        'editor.show_subtitle': 'Показывать исполнителя / сериал',
        'editor.show_year': 'Показывать год',
        'editor.show_runtime': 'Показывать продолжительность',
        'editor.show_rating': 'Показывать рейтинг',
        'editor.show_genres': 'Показывать жанр',
        'editor.show_client': 'Показывать клиент Jellyfin',
        'editor.show_user': 'Показывать пользователя',
        'editor.show_time': 'Показывать прошедшее / оставшееся время',
        'editor.show_background': 'Показывать фон',
        'editor.use_series_image': 'Использовать обложку сериала',
        'editor.show_media_type_badge': 'Показывать значок типа медиа',
        'editor.show_watched_status': 'Показывать статус просмотра',
        'editor.show_date_added': 'Показывать дату добавления',
        'editor.show_description': 'Показывать описание',
        'editor.layout': 'Макет',
        'editor.layout_carousel': 'Карусель',
        'editor.layout_grid': 'Сетка',
        'editor.layout_list': 'Список',
        'editor.media_type': 'Тип медиа',
        'editor.media_type_both': 'Фильмы и Сериалы',
        'editor.media_type_movies': 'Только фильмы',
        'editor.media_type_series': 'Только сериалы',
        'editor.media_type_next_up': 'Далее',
        'editor.tv_content': 'ТВ-контент',
        'editor.tv_content_series': 'Шоу / Сериалы',
        'editor.tv_content_episodes': 'Эпизоды',
        'editor.items_per_page': 'Элементов на странице',
        'editor.max_pages': 'Макс. страниц (0 = без ограничений)',
        'editor.auto_swipe': 'Автопрокрутка (сек, 0 = выкл)',
        'editor.new_badge_days': 'Дней для значка "Новое" (0 = выкл)',
        'editor.click_action': 'Короткое нажатие (Клик)',
        'editor.hold_action': 'Долгое нажатие (Удержание)',
        'editor.double_tap_action': 'Двойное нажатие',
        'editor.action_jellyfin': 'Открыть в Jellyfin',
        'editor.action_cast': 'Трансляция на Chromecast',
        'editor.action_more_info': 'Больше информации',
        'editor.action_trailer': 'Посмотреть трейлер',
        'editor.action_none': 'Нет действия',
        'editor.action_call_service': 'Запустить скрипт',
        'editor.service_to_call': 'Скрипт',
        'editor.service_data': 'Данные сервиса (Опциональный JSON, напр. {"player":"tv"})',
        'editor.default_cast_device': 'Устройство Cast по умолчанию',
        'editor.show_now_playing_overlay': 'Оверлей "Сейчас играет"',
        'editor.metadata_position': 'Расположение метаданных',
        'editor.metadata_below': 'Снизу',
        'editor.metadata_above': 'Сверху',
        'editor.sort_order': 'Порядок сортировки',
        'editor.sort_date_added_desc': 'Дата добавления (Сначала новые)',
        'editor.sort_date_added_asc': 'Дата добавления (Сначала старые)',
        'editor.sort_title_asc': 'Название (А-Я)',
        'editor.sort_title_desc': 'Название (Я-А)',
        'editor.sort_year_desc': 'Год (Сначала новые)',
        'editor.sort_year_asc': 'Год (Сначала старые)',
        'editor.sort_last_played_desc': 'Последний просмотр (Сначала новые)',
        'editor.sort_last_played_asc': 'Последний просмотр (Сначала старые)',
        'editor.enable_pagination': 'Включить пагинацию',
        'editor.show_pagination_dots': 'Показывать точки пагинации',
        'editor.filter_watch_status': 'Фильтр просмотра',
        'editor.filter_all': 'Все',
        'editor.filter_unwatched': 'Непросмотренное',
        'editor.filter_watched': 'Просмотренное',
        'editor.filter_favorites': 'Фильтр избранного',
        'editor.filter_new_items': 'Фильтр новых элементов',
        'editor.columns': 'Столбцы',
        'editor.rows': 'Строки',
        'editor.media_player': 'Медиаплеер',
        'editor.now_playing_sensor': 'Медиаплеер',
        'editor.auto': 'Авто',
        'editor.show_search': 'Показывать панель поиска',
        'editor.show_controls': 'Показывать управление воспроизведением',
        'editor.horizontal_alignment': 'Выравнивание карусели',
        'editor.alignment_center': 'По центру',
        'editor.alignment_left': 'Слева',
        'search.placeholder_title': 'Поиск по названию',
        'search.placeholder_genre': 'Жанр',
        'search.all_genres': 'Все жанры',
    },
};

/**
 * Get localized string
 * @param language - Language code (e.g., 'en', 'de')
 * @param key - Translation key
 * @returns Translated string or key if not found
 */
export function localize(language?: string, key?: string, fallback?: string): string {
    if (!key) return fallback || '';
    const lang = (language || 'en').split('-')[0].toLowerCase();

    // Try exact language
    if (translations[lang]?.[key]) {
        return translations[lang][key];
    }

    // Fallback to English
    if (translations.en?.[key]) {
        return translations.en[key];
    }

    // Return fallback if provided, otherwise empty string (so `localize(...) || 'Default'` triggers)
    return fallback !== undefined ? fallback : '';
}
